#include "core/core.h"
#include "system/keys.h"

using namespace dreavm::system;

struct Key {
  Keycode code;
  const char *name;
};

static Key keys[] = {{K_UNKNOWN, "unknown"},
                     {K_RETURN, "return"},
                     {K_ESCAPE, "escape"},
                     {K_BACKSPACE, "backspace"},
                     {K_TAB, "tab"},
                     {K_SPACE, "space"},
                     {(Keycode)'!', "!"},
                     {(Keycode)'"', "\""},
                     {(Keycode)'#', "#"},
                     {(Keycode)'$', "$"},
                     {(Keycode)'%', "%%"},
                     {(Keycode)'&', "&"},
                     {(Keycode)'\'', "\'"},
                     {(Keycode)'(', "("},
                     {(Keycode)')', ")"},
                     {(Keycode)'*', "*"},
                     {(Keycode)'+', "+"},
                     {(Keycode)',', ","},
                     {(Keycode)'-', "-"},
                     {(Keycode)'.', "."},
                     {(Keycode)'/', "/"},
                     {(Keycode)'0', "0"},
                     {(Keycode)'1', "1"},
                     {(Keycode)'2', "2"},
                     {(Keycode)'3', "3"},
                     {(Keycode)'4', "4"},
                     {(Keycode)'5', "5"},
                     {(Keycode)'6', "6"},
                     {(Keycode)'7', "7"},
                     {(Keycode)'8', "8"},
                     {(Keycode)'9', "9"},
                     {(Keycode)':', ":"},
                     {(Keycode)';', ";"},
                     {(Keycode)'<', "<"},
                     {(Keycode)'=', "="},
                     {(Keycode)'>', ">"},
                     {(Keycode)'?', "?"},
                     {(Keycode)'@', "@"},
                     {(Keycode)'A', "A"},
                     {(Keycode)'B', "B"},
                     {(Keycode)'C', "C"},
                     {(Keycode)'D', "D"},
                     {(Keycode)'E', "E"},
                     {(Keycode)'F', "F"},
                     {(Keycode)'G', "G"},
                     {(Keycode)'H', "H"},
                     {(Keycode)'I', "I"},
                     {(Keycode)'J', "J"},
                     {(Keycode)'K', "K"},
                     {(Keycode)'L', "L"},
                     {(Keycode)'M', "M"},
                     {(Keycode)'N', "N"},
                     {(Keycode)'O', "O"},
                     {(Keycode)'P', "P"},
                     {(Keycode)'Q', "Q"},
                     {(Keycode)'R', "R"},
                     {(Keycode)'S', "S"},
                     {(Keycode)'T', "T"},
                     {(Keycode)'U', "U"},
                     {(Keycode)'V', "V"},
                     {(Keycode)'W', "W"},
                     {(Keycode)'X', "X"},
                     {(Keycode)'Y', "Y"},
                     {(Keycode)'Z', "Z"},
                     {(Keycode)'[', "["},
                     {(Keycode)'\\', "\\"},
                     {(Keycode)']', "]"},
                     {(Keycode)'^', "^"},
                     {(Keycode)'_', "_"},
                     {(Keycode)'`', "`"},
                     {(Keycode)'a', "a"},
                     {(Keycode)'b', "b"},
                     {(Keycode)'c', "c"},
                     {(Keycode)'d', "d"},
                     {(Keycode)'e', "e"},
                     {(Keycode)'f', "f"},
                     {(Keycode)'g', "g"},
                     {(Keycode)'h', "h"},
                     {(Keycode)'i', "i"},
                     {(Keycode)'j', "j"},
                     {(Keycode)'k', "k"},
                     {(Keycode)'l', "l"},
                     {(Keycode)'m', "m"},
                     {(Keycode)'n', "n"},
                     {(Keycode)'o', "o"},
                     {(Keycode)'p', "p"},
                     {(Keycode)'q', "q"},
                     {(Keycode)'r', "r"},
                     {(Keycode)'s', "s"},
                     {(Keycode)'t', "t"},
                     {(Keycode)'u', "u"},
                     {(Keycode)'v', "v"},
                     {(Keycode)'w', "w"},
                     {(Keycode)'x', "x"},
                     {(Keycode)'y', "y"},
                     {(Keycode)'z', "z"},
                     {(Keycode)'{', "{"},
                     {(Keycode)'|', "|"},
                     {(Keycode)'}', "}"},
                     {(Keycode)'~', "~"},
                     {K_CAPSLOCK, "capslock"},
                     {K_F1, "f1"},
                     {K_F2, "f2"},
                     {K_F3, "f3"},
                     {K_F4, "f4"},
                     {K_F5, "f5"},
                     {K_F6, "f6"},
                     {K_F7, "f7"},
                     {K_F8, "f8"},
                     {K_F9, "f9"},
                     {K_F10, "f10"},
                     {K_F11, "f11"},
                     {K_F12, "f12"},
                     {K_PRINTSCREEN, "printscreen"},
                     {K_SCROLLLOCK, "scrolllock"},
                     {K_PAUSE, "pause"},
                     {K_INSERT, "inser"},
                     {K_HOME, "home"},
                     {K_PAGEUP, "pageup"},
                     {K_DELETE, "delete"},
                     {K_END, "end"},
                     {K_PAGEDOWN, "pagedown"},
                     {K_RIGHT, "right"},
                     {K_LEFT, "left"},
                     {K_DOWN, "down"},
                     {K_UP, "up"},
                     {K_NUMLOCKCLEAR, "numlockclear"},
                     {K_KP_DIVIDE, "kp_divide"},
                     {K_KP_MULTIPLY, "kp_multiply"},
                     {K_KP_MINUS, "kp_minus"},
                     {K_KP_PLUS, "kp_plus"},
                     {K_KP_ENTER, "kp_enter"},
                     {K_KP_1, "kp_1"},
                     {K_KP_2, "kp_2"},
                     {K_KP_3, "kp_3"},
                     {K_KP_4, "kp_4"},
                     {K_KP_5, "kp_5"},
                     {K_KP_6, "kp_6"},
                     {K_KP_7, "kp_7"},
                     {K_KP_8, "kp_8"},
                     {K_KP_9, "kp_9"},
                     {K_KP_0, "kp_0"},
                     {K_KP_PERIOD, "kp_period"},
                     {K_APPLICATION, "application"},
                     {K_POWER, "power"},
                     {K_KP_EQUALS, "kp_equals"},
                     {K_F13, "f13"},
                     {K_F14, "f14"},
                     {K_F15, "f15"},
                     {K_F16, "f16"},
                     {K_F17, "f17"},
                     {K_F18, "f18"},
                     {K_F19, "f19"},
                     {K_F20, "f20"},
                     {K_F21, "f21"},
                     {K_F22, "f22"},
                     {K_F23, "f23"},
                     {K_F24, "f24"},
                     {K_EXECUTE, "execute"},
                     {K_HELP, "help"},
                     {K_MENU, "menu"},
                     {K_SELECT, "select"},
                     {K_STOP, "stop"},
                     {K_AGAIN, "again"},
                     {K_UNDO, "undo"},
                     {K_CUT, "cut"},
                     {K_COPY, "copy"},
                     {K_PASTE, "paste"},
                     {K_FIND, "find"},
                     {K_MUTE, "mute"},
                     {K_VOLUMEUP, "volumeup"},
                     {K_VOLUMEDOWN, "volumedown"},
                     {K_KP_COMMA, "kp_comma"},
                     {K_KP_EQUALSAS400, "kp_equalsas400"},
                     {K_ALTERASE, "alterase"},
                     {K_SYSREQ, "sysreq"},
                     {K_CANCEL, "cancel"},
                     {K_CLEAR, "clear"},
                     {K_PRIOR, "prior"},
                     {K_RETURN2, "return2"},
                     {K_SEPARATOR, "separator"},
                     {K_OUT, "out"},
                     {K_OPER, "oper"},
                     {K_CLEARAGAIN, "clearagain"},
                     {K_CRSEL, "crsel"},
                     {K_EXSEL, "exsel"},
                     {K_KP_00, "kp_00"},
                     {K_KP_000, "kp_000"},
                     {K_THOUSANDSSEPARATOR, "thousandsseparator"},
                     {K_DECIMALSEPARATOR, "decimalseparator"},
                     {K_CURRENCYUNIT, "currencyunit"},
                     {K_CURRENCYSUBUNIT, "currencysubunit"},
                     {K_KP_LEFTPAREN, "kp_leftparen"},
                     {K_KP_RIGHTPAREN, "kp_rightparen"},
                     {K_KP_LEFTBRACE, "kp_leftbrace"},
                     {K_KP_RIGHTBRACE, "kp_rightbrace"},
                     {K_KP_TAB, "kp_tab"},
                     {K_KP_BACKSPACE, "kp_backspace"},
                     {K_KP_A, "kp_a"},
                     {K_KP_B, "kp_b"},
                     {K_KP_C, "kp_c"},
                     {K_KP_D, "kp_d"},
                     {K_KP_E, "kp_e"},
                     {K_KP_F, "kp_f"},
                     {K_KP_XOR, "kp_xor"},
                     {K_KP_POWER, "kp_power"},
                     {K_KP_PERCENT, "kp_percent"},
                     {K_KP_LESS, "kp_less"},
                     {K_KP_GREATER, "kp_greater"},
                     {K_KP_AMPERSAND, "kp_ampersand"},
                     {K_KP_DBLAMPERSAND, "kp_dblampersand"},
                     {K_KP_VERTICALBAR, "kp_verticalbar"},
                     {K_KP_DBLVERTICALBAR, "kp_dblverticalbar"},
                     {K_KP_COLON, "kp_colon"},
                     {K_KP_HASH, "kp_hash"},
                     {K_KP_SPACE, "kp_space"},
                     {K_KP_AT, "kp_at"},
                     {K_KP_EXCLAM, "kp_exclam"},
                     {K_KP_MEMSTORE, "kp_memstore"},
                     {K_KP_MEMRECALL, "kp_memrecall"},
                     {K_KP_MEMCLEAR, "kp_memclear"},
                     {K_KP_MEMADD, "kp_memadd"},
                     {K_KP_MEMSUBTRACT, "kp_memsubtract"},
                     {K_KP_MEMMULTIPLY, "kp_memmultiply"},
                     {K_KP_MEMDIVIDE, "kp_memdivide"},
                     {K_KP_PLUSMINUS, "kp_plusminus"},
                     {K_KP_CLEAR, "kp_clear"},
                     {K_KP_CLEARENTRY, "kp_clearentry"},
                     {K_KP_BINARY, "kp_binary"},
                     {K_KP_OCTAL, "kp_octal"},
                     {K_KP_DECIMAL, "kp_decimal"},
                     {K_KP_HEXADECIMAL, "kp_hexadecimal"},
                     {K_LCTRL, "lctrl"},
                     {K_LSHIFT, "lshift"},
                     {K_LALT, "lalt"},
                     {K_LGUI, "lgui"},
                     {K_RCTRL, "rctrl"},
                     {K_RSHIFT, "rshift"},
                     {K_RALT, "ralt"},
                     {K_RGUI, "rgui"},
                     {K_MODE, "mode"},
                     {K_AUDIONEXT, "audionext"},
                     {K_AUDIOPREV, "audioprev"},
                     {K_AUDIOSTOP, "audiostop"},
                     {K_AUDIOPLAY, "audioplay"},
                     {K_AUDIOMUTE, "audiomute"},
                     {K_MEDIASELECT, "mediaselect"},
                     {K_WWW, "www"},
                     {K_MAIL, "mail"},
                     {K_CALCULATOR, "calculator"},
                     {K_COMPUTER, "computer"},
                     {K_AC_SEARCH, "ac_search"},
                     {K_AC_HOME, "ac_home"},
                     {K_AC_BACK, "ac_back"},
                     {K_AC_FORWARD, "ac_forward"},
                     {K_AC_STOP, "ac_stop"},
                     {K_AC_REFRESH, "ac_refresh"},
                     {K_AC_BOOKMARKS, "ac_bookmarks"},
                     {K_BRIGHTNESSDOWN, "brightnessdown"},
                     {K_BRIGHTNESSUP, "brightnessup"},
                     {K_DISPLAYSWITCH, "displayswitch"},
                     {K_KBDILLUMTOGGLE, "kbdillumtoggle"},
                     {K_KBDILLUMDOWN, "kbdillumdown"},
                     {K_KBDILLUMUP, "kbdillumup"},
                     {K_EJECT, "eject"},
                     {K_SLEEP, "sleep"},
                     {K_MOUSE1, "mouse1"},
                     {K_MOUSE2, "mouse2"},
                     {K_MOUSE3, "mouse3"},
                     {K_MOUSE4, "mouse4"},
                     {K_MOUSE5, "mouse5"},
                     {K_MWHEELUP, "mwheelup"},
                     {K_MWHEELDOWN, "mwheeldown"},
                     {K_JOY0, "joy0"},
                     {K_JOY1, "joy1"},
                     {K_JOY2, "joy2"},
                     {K_JOY3, "joy3"},
                     {K_JOY4, "joy4"},
                     {K_JOY5, "joy5"},
                     {K_JOY6, "joy6"},
                     {K_JOY7, "joy7"},
                     {K_JOY8, "joy8"},
                     {K_JOY9, "joy9"},
                     {K_JOY10, "joy10"},
                     {K_JOY11, "joy11"},
                     {K_JOY12, "joy12"},
                     {K_JOY13, "joy13"},
                     {K_JOY14, "joy14"},
                     {K_JOY15, "joy15"},
                     {K_JOY16, "joy16"},
                     {K_JOY17, "joy17"},
                     {K_JOY18, "joy18"},
                     {K_JOY19, "joy19"},
                     {K_JOY20, "joy20"},
                     {K_JOY21, "joy21"},
                     {K_JOY22, "joy22"},
                     {K_JOY23, "joy23"},
                     {K_JOY24, "joy24"},
                     {K_JOY25, "joy25"},
                     {K_JOY26, "joy26"},
                     {K_JOY27, "joy27"},
                     {K_JOY28, "joy28"},
                     {K_JOY29, "joy29"},
                     {K_JOY30, "joy30"},
                     {K_JOY31, "joy31"},
                     {K_AXIS0, "axis0"},
                     {K_AXIS1, "axis1"},
                     {K_AXIS2, "axis2"},
                     {K_AXIS3, "axis3"},
                     {K_AXIS4, "axis4"},
                     {K_AXIS5, "axis5"},
                     {K_AXIS6, "axis6"},
                     {K_AXIS7, "axis7"},
                     {K_AXIS8, "axis8"},
                     {K_AXIS9, "axis9"},
                     {K_AXIS10, "axis10"},
                     {K_AXIS11, "axis11"},
                     {K_AXIS12, "axis12"},
                     {K_AXIS13, "axis13"},
                     {K_AXIS14, "axis14"},
                     {K_AXIS15, "axis15"}};

Keycode dreavm::system::GetKeycodeByName(const char *keyname) {
  char buffer[256] = {0};
  int len = 0;

  while (*keyname) {
    buffer[len++] = tolower(*keyname);
    keyname++;
  }

  for (size_t i = 0, l = sizeof(keys) / sizeof(Key); i < l; i++) {
    const Key &key = keys[i];

    if (!strcmp(key.name, buffer)) {
      return key.code;
    }
  }

  return K_UNKNOWN;
}

const char *dreavm::system::GetNameByKeycode(Keycode keycode) {
  static const char *unknown = "unknown";

  for (size_t i = 0, l = sizeof(keys) / sizeof(Key); i < l; i++) {
    const Key &key = keys[i];

    if (key.code == keycode) {
      return key.name;
    }
  }

  return unknown;
}
