#include "keycode.h"
#include "core/string.h"

struct key {
  enum keycode code;
  const char *name;
};

static struct key keys[] = {{K_UNKNOWN, "unknown"},
                            {K_SPACE, "space"},
                            {(enum keycode)'!', "!"},
                            {(enum keycode)'"', "\""},
                            {(enum keycode)'#', "#"},
                            {(enum keycode)'$', "$"},
                            {(enum keycode)'%', "%%"},
                            {(enum keycode)'&', "&"},
                            {(enum keycode)'\'', "\'"},
                            {(enum keycode)'(', "("},
                            {(enum keycode)')', ")"},
                            {(enum keycode)'*', "*"},
                            {(enum keycode)'+', "+"},
                            {(enum keycode)',', ","},
                            {(enum keycode)'-', "-"},
                            {(enum keycode)'.', "."},
                            {(enum keycode)'/', "/"},
                            {(enum keycode)'0', "0"},
                            {(enum keycode)'1', "1"},
                            {(enum keycode)'2', "2"},
                            {(enum keycode)'3', "3"},
                            {(enum keycode)'4', "4"},
                            {(enum keycode)'5', "5"},
                            {(enum keycode)'6', "6"},
                            {(enum keycode)'7', "7"},
                            {(enum keycode)'8', "8"},
                            {(enum keycode)'9', "9"},
                            {(enum keycode)':', ":"},
                            {(enum keycode)';', ";"},
                            {(enum keycode)'<', "<"},
                            {(enum keycode)'=', "="},
                            {(enum keycode)'>', ">"},
                            {(enum keycode)'?', "?"},
                            {(enum keycode)'@', "@"},
                            {(enum keycode)'[', "["},
                            {(enum keycode)'\\', "\\"},
                            {(enum keycode)']', "]"},
                            {(enum keycode)'^', "^"},
                            {(enum keycode)'_', "_"},
                            {(enum keycode)'`', "`"},
                            {(enum keycode)'A', "a"},
                            {(enum keycode)'B', "b"},
                            {(enum keycode)'C', "c"},
                            {(enum keycode)'D', "d"},
                            {(enum keycode)'E', "e"},
                            {(enum keycode)'F', "f"},
                            {(enum keycode)'G', "g"},
                            {(enum keycode)'H', "h"},
                            {(enum keycode)'I', "i"},
                            {(enum keycode)'J', "j"},
                            {(enum keycode)'K', "k"},
                            {(enum keycode)'L', "l"},
                            {(enum keycode)'M', "m"},
                            {(enum keycode)'N', "n"},
                            {(enum keycode)'O', "o"},
                            {(enum keycode)'P', "p"},
                            {(enum keycode)'Q', "q"},
                            {(enum keycode)'R', "r"},
                            {(enum keycode)'S', "s"},
                            {(enum keycode)'T', "t"},
                            {(enum keycode)'U', "u"},
                            {(enum keycode)'V', "v"},
                            {(enum keycode)'W', "w"},
                            {(enum keycode)'X', "x"},
                            {(enum keycode)'Y', "y"},
                            {(enum keycode)'Z', "z"},
                            {(enum keycode)'{', "{"},
                            {(enum keycode)'|', "|"},
                            {(enum keycode)'}', "}"},
                            {(enum keycode)'~', "~"},
                            {K_ESCAPE, "escape"},
                            {K_ENTER, "enter"},
                            {K_TAB, "tab"},
                            {K_BACKSPACE, "backspace"},
                            {K_INSERT, "insert"},
                            {K_DELETE, "delete"},
                            {K_RIGHT, "right"},
                            {K_LEFT, "left"},
                            {K_DOWN, "down"},
                            {K_UP, "up"},
                            {K_PAGE_UP, "pageup"},
                            {K_PAGE_DOWN, "pagedown"},
                            {K_HOME, "home"},
                            {K_END, "end"},
                            {K_CAPS_LOCK, "capslock"},
                            {K_SCROLL_LOCK, "scrolllock"},
                            {K_NUM_LOCK, "numlock"},
                            {K_PRINT_SCREEN, "printscreen"},
                            {K_PAUSE, "pause"},
                            {K_F1, "f1"},
                            {K_F2, "f2"},
                            {K_F3, "f3"},
                            {K_F4, "f4"},
                            {K_F5, "f5"},
                            {K_F6, "f6"},
                            {K_F7, "f7"},
                            {K_F8, "f8"},
                            {K_F9, "f9"},
                            {K_F10, "f10"},
                            {K_F11, "f11"},
                            {K_F12, "f12"},
                            {K_F13, "f13"},
                            {K_F14, "f14"},
                            {K_F15, "f15"},
                            {K_F16, "f16"},
                            {K_F17, "f17"},
                            {K_F18, "f18"},
                            {K_F19, "f19"},
                            {K_F20, "f20"},
                            {K_F21, "f21"},
                            {K_F22, "f22"},
                            {K_F23, "f23"},
                            {K_F24, "f24"},
                            {K_F25, "f25"},
                            {K_KP_0, "kp_0"},
                            {K_KP_1, "kp_1"},
                            {K_KP_2, "kp_2"},
                            {K_KP_3, "kp_3"},
                            {K_KP_4, "kp_4"},
                            {K_KP_5, "kp_5"},
                            {K_KP_6, "kp_6"},
                            {K_KP_7, "kp_7"},
                            {K_KP_8, "kp_8"},
                            {K_KP_9, "kp_9"},
                            {K_KP_DECIMAL, "kp_decimal"},
                            {K_KP_DIVIDE, "kp_divide"},
                            {K_KP_MULTIPLY, "kp_multiply"},
                            {K_KP_SUBTRACT, "kp_subtract"},
                            {K_KP_ADD, "kp_add"},
                            {K_KP_ENTER, "kp_enter"},
                            {K_KP_EQUAL, "kp_equal"},
                            {K_LEFT_SHIFT, "lshift"},
                            {K_LEFT_CONTROL, "lctrl"},
                            {K_LEFT_ALT, "lalt"},
                            {K_LEFT_SUPER, "lsuper"},
                            {K_RIGHT_SHIFT, "lshift"},
                            {K_RIGHT_CONTROL, "lctrl"},
                            {K_RIGHT_ALT, "lalt"},
                            {K_RIGHT_SUPER, "lsuper"},
                            {K_MENU, "menu"},
                            {K_MOUSE1, "mouse1"},
                            {K_MOUSE2, "mouse2"},
                            {K_MOUSE3, "mouse3"},
                            {K_MOUSE4, "mouse4"},
                            {K_MOUSE5, "mouse5"},
                            {K_MWHEELUP, "mwheelup"},
                            {K_MWHEELDOWN, "mwheeldown"},
                            {K_JOY0, "joy0"},
                            {K_JOY1, "joy1"},
                            {K_JOY2, "joy2"},
                            {K_JOY3, "joy3"},
                            {K_JOY4, "joy4"},
                            {K_JOY5, "joy5"},
                            {K_JOY6, "joy6"},
                            {K_JOY7, "joy7"},
                            {K_JOY8, "joy8"},
                            {K_JOY9, "joy9"},
                            {K_JOY10, "joy10"},
                            {K_JOY11, "joy11"},
                            {K_JOY12, "joy12"},
                            {K_JOY13, "joy13"},
                            {K_JOY14, "joy14"},
                            {K_JOY15, "joy15"},
                            {K_JOY16, "joy16"},
                            {K_JOY17, "joy17"},
                            {K_JOY18, "joy18"},
                            {K_JOY19, "joy19"},
                            {K_JOY20, "joy20"},
                            {K_JOY21, "joy21"},
                            {K_JOY22, "joy22"},
                            {K_JOY23, "joy23"},
                            {K_JOY24, "joy24"},
                            {K_JOY25, "joy25"},
                            {K_JOY26, "joy26"},
                            {K_JOY27, "joy27"},
                            {K_JOY28, "joy28"},
                            {K_JOY29, "joy29"},
                            {K_JOY30, "joy30"},
                            {K_JOY31, "joy31"},
                            {K_HAT0, "hat0"},
                            {K_HAT1, "hat1"},
                            {K_HAT2, "hat2"},
                            {K_HAT3, "hat3"},
                            {K_HAT4, "hat4"},
                            {K_HAT5, "hat5"},
                            {K_HAT6, "hat6"},
                            {K_HAT7, "hat7"},
                            {K_HAT8, "hat8"},
                            {K_HAT9, "hat9"},
                            {K_HAT10, "hat10"},
                            {K_HAT11, "hat11"},
                            {K_HAT12, "hat12"},
                            {K_HAT13, "hat13"},
                            {K_HAT14, "hat14"},
                            {K_HAT15, "hat15"},
                            {K_AXIS0, "axis0"},
                            {K_AXIS1, "axis1"},
                            {K_AXIS2, "axis2"},
                            {K_AXIS3, "axis3"},
                            {K_AXIS4, "axis4"},
                            {K_AXIS5, "axis5"},
                            {K_AXIS6, "axis6"},
                            {K_AXIS7, "axis7"},
                            {K_AXIS8, "axis8"},
                            {K_AXIS9, "axis9"},
                            {K_AXIS10, "axis10"},
                            {K_AXIS11, "axis11"},
                            {K_AXIS12, "axis12"},
                            {K_AXIS13, "axis13"},
                            {K_AXIS14, "axis14"},
                            {K_AXIS15, "axis15"},
                            {K_AXIS16, "axis16"},
                            {K_AXIS17, "axis17"},
                            {K_AXIS18, "axis18"},
                            {K_AXIS19, "axis19"},
                            {K_AXIS20, "axis20"},
                            {K_AXIS21, "axis21"},
                            {K_AXIS22, "axis22"},
                            {K_AXIS23, "axis23"},
                            {K_AXIS24, "axis24"},
                            {K_AXIS25, "axis25"}};

enum keycode get_key_by_name(const char *keyname) {
  char buffer[256] = {0};
  int len = 0;

  while (*keyname) {
    buffer[len++] = tolower(*keyname);
    keyname++;
  }

  for (size_t i = 0, l = sizeof(keys) / sizeof(struct key); i < l; i++) {
    const struct key *key = &keys[i];

    if (!strcmp(key->name, buffer)) {
      return key->code;
    }
  }

  return K_UNKNOWN;
}

const char *get_name_by_key(enum keycode keycode) {
  static const char *unknown = "unknown";

  for (size_t i = 0, l = sizeof(keys) / sizeof(struct key); i < l; i++) {
    const struct key *key = &keys[i];

    if (key->code == keycode) {
      return key->name;
    }
  }

  return unknown;
}
