#include "stats.h"

DEFINE_AGGREGATE_COUNTER(frames);
DEFINE_AGGREGATE_COUNTER(aica_samples);
DEFINE_AGGREGATE_COUNTER(arm7_instrs);
DEFINE_AGGREGATE_COUNTER(pvr_vblanks);
DEFINE_AGGREGATE_COUNTER(ta_renders);
DEFINE_AGGREGATE_COUNTER(sh4_instrs);
